name: Check for OFAC update (beta)

on:
  schedule:
    - cron: '0 */12 * * *'
  push:
    branches:
      - main

jobs:
  check-for-ofac-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm install -g linkinator
      - run: linkinator -r https://docs.flashbots.net
