name: PR Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Test build
        env:
          TARGET_URL: "https://docs.flashbots.net"
          BASE_URL: "/"
        run: |
          yarn install --frozen-lockfile
          yarn build
      - name: Check for broken links
        run: |
          cd build
          npm install -g linkinator
          linkinator -r *.html **/*.html -s https://dune.com/ChainsightAnalytics
