name: PR Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: oven-sh/setup-bun@v1
      - name: Test build
        env:
          TARGET_URL: "https://docs.flashbots.net"
          BASE_URL: "/"
          ALGOLIA_APP_ID: "example"
          ALGOLIA_SEARCH_API_KEY: "example"
          ALGOLIA_INDEX_NAME: "example"
        run: |
          bun install --frozen-lockfile
          bun run build
      # - name: Check for broken links
      #   run: |
      #     cd build
      #     npm install -g linkinator
      #     linkinator "**/*.html" --recurse --timeout 3000 --concurrency 10 --retry -s https://dune.com/ChainsightAnalytics,'https://.*etherscan.io/.*','https://twitter.com.*','https://.*imgur.com.*'
